In [1]:

%matplotlib inline
from pandas import Series, DataFrame
import pandas as pd
import operator
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
from scipy.spatial.distance import cosine

In [2]:
file_dir = 'Assignment 6.xls'
items = pd.read_excel(file_dir, sheetname = "Items")
users = pd.read_excel(file_dir, sheetname = "Users")

In [3]:
#Quiz1
items[1].sort_values(ascending= False)[1:6]

4327  Charlie's Angels (2000)              0.281990
414   Batman Forever (1995)                0.218089
3049  Ace Ventura: Pet Detective (1994)    0.190879
8467  Dumb & Dumber (1994)                 0.190638
854   The Mask (1994)                      0.158601
Name: 1, dtype: float64

In [4]:
#Quiz2
items[2].sort_values(ascending= False)[1:6]

14   American Beauty (1999)                          0.198715
680  Pulp Fiction (1994)                             0.189565
24   Kill Bill: Vol. 1 (2003)                        0.181570
275  Fargo (1996)                                    0.161559
38   Eternal Sunshine of the Spotless Mind (2004)    0.161058
Name: 2, dtype: float64

In [5]:
#Quiz3
d = dict()
weight = [203.6150217,121.0212568,102.7978818,96.83082284, 85.13373768, 82.76380819, 79.83500014,77.66641961,74.60701813,
          73.10941039, 69.09655995,68.13658784,66.48030495,64.51308808, 63.56943648]
for i in range(2,102):
    d[items.iloc[i][:2].name ] = (np.mat(items.iloc[i] * weight) *np.mat(users.iloc[8][1:]).T).item(0)
    
data = pd.DataFrame(d.items())
data.sort(1, ascending = False)

User    4469.000000
1         -0.002139
2         -0.001049
3         -0.004224
4         -0.001461
5          0.003396
6          0.001352
7         -0.000004
8         -0.001165
9         -0.000785
10        -0.002333
11        -0.001737
12         0.001324
13         0.002993
14         0.000662
15        -0.001001
Name: 8, dtype: float64

/Library/Python/2.7/site-packages/ipykernel/__main__.py:10: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

                                                    0         1
14             (278, The Shawshank Redemption (1994))  0.207680
59                     (453, A Beautiful Mind (2001))  0.183286
44                             (98, Gladiator (2000))  0.173611
69                        (238, The Godfather (1972))  0.172180
57                          (13, Forrest Gump (1994))  0.170744
35                     (424, Schindler's List (1993))  0.158589
51                           (197, Braveheart (1995))  0.154786
91                      (155, The Dark Knight (2008))  0.145577
5                               (597, Titanic (1997))  0.140433
22                  (857, Saving Private Ryan (1998))  0.122192
12                        (1422, The Departed (2006))  0.109095
38                           (550, Fight Club (1999))  0.096004
32                  (640, Catch Me If You Can (2002))  0.087335
19             (274, The Silence of the Lambs (1991))  0.085421
18                           (8358, Cast Away (2000))  0.073535
65                        (272, Batman Begins (2005))  0.072513
21                         (2024, The Patriot (2000))  0.065811
85  (1894, Star Wars: Episode II - Attack of the C...  0.065049
93                 (807, Seven (a.k.a. Se7en) (1995))  0.060511
39                 (2501, The Bourne Identity (2002))  0.060159
0                 (2502, The Bourne Supremacy (2004))  0.058185
74                       (8587, The Lion King (1994))  0.056708
8                       (745, The Sixth Sense (1999))  0.051693
52                   (581, Dances with Wolves (1990))  0.051679
36                         (680, Pulp Fiction (1994))  0.048448
97  (122, The Lord of the Rings: The Return of the...  0.041189
72                       (161, Ocean's Eleven (2001))  0.038589
71                   (629, The Usual Suspects (1995))  0.037713
13                               (77, Memento (2000))  0.034110
56    (11, Star Wars: Episode IV - A New Hope (1977))  0.033540
..                                                ...       ...
2                               (664, Twister (1996)) -0.042339
70                              (812, Aladdin (1992)) -0.043510
48                        (786, Almost Famous (2000)) -0.045272
53               (10020, Beauty and the Beast (1991)) -0.046253
40           (280, Terminator 2: Judgment Day (1991)) -0.046342
11          (1572, Die Hard: With a Vengeance (1995)) -0.046762
98           (601, E.T. the Extra-Terrestrial (1982)) -0.047093
95                              (36657, X-Men (2000)) -0.052109
78                             (187, Sin City (2005)) -0.054131
24  (85, Raiders of the Lost Ark (Indiana Jones an... -0.054850
66                   (36658, X2: X-Men United (2003)) -0.057458
45                   (105, Back to the Future (1985)) -0.060360
27                          (12, Finding Nemo (2003)) -0.066459
88  (672, Harry Potter and the Chamber of Secrets ... -0.069166
4                              (854, The Mask (1994)) -0.075315
6                           (36955, True Lies (1994)) -0.076232
20  (146, Crouching Tiger Hidden Dragon (Wo hu can... -0.076520
75  (671, Harry Potter and the Sorcerer's Stone (a... -0.085070
33                         (7443, Chicken Run (2000)) -0.092541
1                                 (808, Shrek (2001)) -0.097637
49                           (557, Spider-Man (2002)) -0.100990
42                              (809, Shrek 2 (2004)) -0.101059
46                            (862, Toy Story (1995)) -0.101166
58                    (393, Kill Bill: Vol. 2 (2004)) -0.104043
3                      (24, Kill Bill: Vol. 1 (2003)) -0.113526
61                        (585, Monsters Inc. (2001)) -0.114932
7                          (558, Spider-Man 2 (2004)) -0.122341
76                     (9806, The Incredibles (2004)) -0.131435
67            (607, Men in Black (a.k.a. MIB) (1997)) -0.142724
79                    (4327, Charlie's Angels (2000)) -0.199980

[100 rows x 2 columns]